// @generated by protobuf-ts 2.9.1
// @generated from protobuf file "proto/pandt.proto" (package "pandt", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PT } from "./pandt";
import type { ListSavedGamesReply } from "./pandt";
import type { Empty } from "./pandt";
import type { SaveGameRequest } from "./pandt";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HelloReply } from "./pandt";
import type { HelloRequest } from "./pandt";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service pandt.PT
 */
export interface IPTClient {
    /**
     * Our SayHello rpc accepts HelloRequests and returns HelloReplies
     *
     * @generated from protobuf rpc: SayHello(pandt.HelloRequest) returns (pandt.HelloReply);
     */
    sayHello(input: HelloRequest, options?: RpcOptions): UnaryCall<HelloRequest, HelloReply>;
    /**
     * @generated from protobuf rpc: SaveGame(pandt.SaveGameRequest) returns (pandt.Empty);
     */
    saveGame(input: SaveGameRequest, options?: RpcOptions): UnaryCall<SaveGameRequest, Empty>;
    /**
     * @generated from protobuf rpc: ListSavedGames(pandt.Empty) returns (pandt.ListSavedGamesReply);
     */
    listSavedGames(input: Empty, options?: RpcOptions): UnaryCall<Empty, ListSavedGamesReply>;
}
/**
 * @generated from protobuf service pandt.PT
 */
export class PTClient implements IPTClient, ServiceInfo {
    typeName = PT.typeName;
    methods = PT.methods;
    options = PT.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Our SayHello rpc accepts HelloRequests and returns HelloReplies
     *
     * @generated from protobuf rpc: SayHello(pandt.HelloRequest) returns (pandt.HelloReply);
     */
    sayHello(input: HelloRequest, options?: RpcOptions): UnaryCall<HelloRequest, HelloReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HelloRequest, HelloReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveGame(pandt.SaveGameRequest) returns (pandt.Empty);
     */
    saveGame(input: SaveGameRequest, options?: RpcOptions): UnaryCall<SaveGameRequest, Empty> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SaveGameRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListSavedGames(pandt.Empty) returns (pandt.ListSavedGamesReply);
     */
    listSavedGames(input: Empty, options?: RpcOptions): UnaryCall<Empty, ListSavedGamesReply> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ListSavedGamesReply>("unary", this._transport, method, opt, input);
    }
}
