version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - docker pull ekidd/rust-musl-builder:beta
      - mkdir -p docker/cache/cargo_git
      - mkdir -p docker/cache/cargo_registry
      - mkdir -p docker/cache/cargo_target
      - rm -f CIDFILE

  build:
    commands:
      - docker build -t pandt-lambda -f docker/lambda-builder.dockerfile .
      - docker run --cidfile CIDFILE -v "$(pwd)/docker/cache/cargo_git:/home/rust/.cargo/git" -v "$(pwd)/docker/cache/cargo_registry:/home/rust/.cargo/registry" -v "$(pwd)/docker/cache/cargo_target:/home/rust/src/target" pandt-lambda:latest
      - mkdir artifacts
      - docker cp $(cat CIDFILE):/home/rust/src/target/x86_64-unknown-linux-musl/release/pandt_lambda artifacts/
      - cd artifacts
      - zip pandt_lambda.zip pandt_lambda
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - artifacts/pandt_lambda.zip
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
