AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    P&T lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10


Resources:

    pandt:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            FunctionName: pandt
            CodeUri: artifacts/
            Handler: lollerskates # This is unused in the `provided` runtime
            Runtime: provided
            Role: "arn:aws:iam::078122003867:role/service-role/pandt-lambda"
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    _LAMBDA_SERVER_PORT: "5000"
                    RUST_BACKTRACE: "1"
            Events:
                pandt:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: get

Outputs:

    pandt_api:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    pandt_function:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt pandt_function.Arn
