[package]
name = "ptrpi"
version = "0.1.0"
authors = ["Christopher Armstrong"]
edition = "2018"

[dependencies]
async-std = {version = "1.4", features = ["attributes"]}
env_logger = "0.7"
failure = "0.1"
failure_derive = "0.1"
foldertree = {version = "*", path = "../foldertree"}
log = "0.4.8"
pandt = {version = "*", path = "../pandt"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
tide = "0.5"
http = "0.2.0"
