// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttrID } from "./AttrID";
import type { SkillLevel } from "./SkillLevel";

export interface AttributeCheck { reliable: boolean, attr: AttrID, target: SkillLevel, }