// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureID } from "./CreatureID";
import type { Point3 } from "./Point3";

export type DecidedTarget = { Creature: CreatureID } | { Creatures: Array<CreatureID> } | "Actor" | { Point: Point3 };