// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbilityID } from "./AbilityID";
import type { ClassID } from "./ClassID";
import type { CreatureID } from "./CreatureID";
import type { ItemID } from "./ItemID";
import type { SceneID } from "./SceneID";

export type FolderItemID = { SceneID: SceneID } | { CreatureID: CreatureID } | { NoteID: string } | { ItemID: ItemID } | { AbilityID: AbilityID } | { ClassID: ClassID } | { SubfolderID: string };