name = "arpeggio-backend"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"
logpush = true

[build]
command = "node ./build.js"


[durable_objects]
bindings = [
  { name = "ARPEGGIOGAME", class_name = "ArpeggioGame" },
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ArpeggioGame"] # Array of new classes

[vars]
GOOGLE_CLIENT_ID = "328154234071-c7una5er0n385sdgvih81ngbkgp1l7nj.apps.googleusercontent.com"
CF_ACCOUNT_ID = "9da1987464827a8209f127a4e0f02b77"
CF_IMAGE_DELIVERY_PREFIX = "https://arpeggiogame.com/cdn-cgi/imagedelivery/0DU4Tw-CmEbMyEuTLNg6Xg/"

[[d1_databases]]
binding = "DB"
database_name = "arpeggio-users"
database_id = "9bbbb737-cabc-44cb-bd76-44c3a5625759"
