name: Docker

on: [workflow-dispatch] # disabling since I've switched to workers

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: docker build . -t ptrpi
