name: UI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: NPM install
      working-directory: ./ui
      run: npm install
    - name: TypeScript Compiler
      working-directory: ./ui
      run: npm run typecheck
    - name: UI Unit Tests
      working-directory: ./ui
      run: npm run test run
